name: Release

on:
  push:
  pull_request:
  schedule:
    - cron: "22 11 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install requirements
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y gettext

      - name: tx push / pull
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          curl -OL https://github.com/transifex/cli/releases/download/v1.3.1/tx-linux-amd64.tar.gz
          tar -xvzf tx-linux-amd64.tar.gz
          make gettext
          make transifex_pull

      - name: build
        run: |
          make html
          touch build/html/.nojekyll

      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/html
