on:
  schedule:
    - cron: "5 1 * * *"
  workflow_dispatch:

jobs:
  translations-pull:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Requirements
        run: |
          sudo apt-get install -y qttools5-dev-tools
          # v1.6.5: 2023-02-16
          curl -OL https://github.com/transifex/cli/releases/download/v1.6.5/tx-linux-amd64.tar.gz
          tar -xvzf tx-linux-amd64.tar.gz

      - name: Pull translations from transifex
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: .\tx pull --all --minimum-perc 50

      - uses: EndBug/add-and-commit@v9
        with:
          message: Synchronize translations
          author_name: Translation update
          author_email: info@opengis.ch
